const _ = require('node-validator')

module.exports = _.isObject()
  .withOptional('first_name', _.isString())
  .withOptional('last_name', _.isString())
  .withOptional('gender', _.isString())
  .withOptional('email', _.isString())
  .withOptional('password', _.isString())
  .withOptional('age', _.isNumber({min: 0, max: 120}))
  .withOptional('height', _.isNumber())
  .withOptional('weight', _.isNumber())
  .withOptional('city', _.isString())
  .withOptional('city_code', _.isString())
  .withOptional('street_number', _.isNumber())
  .withOptional('street_type', _.isString())
  .withOptional('street_name', _.isString())
  .withOptional('phone', _.isString())
  .withOptional('image_profil', _.isString())
